### ISSUE TITLE
Filtro Precios

### ISSUE THREAD

**Issue by argomir** [Unioviedu/SDM_iListPro#7]
Si activamos los dos filtros y el precio minimo es mayor que el menor no aparece ningun producto (logico), pero lo dejamos asi o lo cambiamos para que no pueda ocurrir nunca?

**Comment by argomir** [comment]
Y me acabo de dar cuenta, poniendo el filtro minimo a 10 y el maximo a 30, aparecen 4 productos en la seccion de carne, pero en el apartado "todo" no aparece ninguno.

**Comment by Unioviedu** [comment]
Arreglado, había puesto un break donde era un continue
